import type { MockInventory } from './types';

export const mockInventory: MockInventory = {
  kiosk_1: {
    kiosk_id: 'kiosk_1',
    kiosk_name: 'Mid Valley Food Court',
    items: [
      {
        item_id: 'EGG001',
        item_name: 'Eggs',
        category: 'Protein',
        unit: 'dozen',
        icon: '🥚',
        current_stock: 10,
        min_stock: 2,
        max_stock: 15,
        expiry_date: '2026-05-10',
        rack_position: 'fridge_A1',
      },
      {
        item_id: 'CHICK001',
        item_name: 'Chicken',
        category: 'Protein',
        unit: 'kg',
        icon: '🍗',
        current_stock: 3,
        min_stock: 5,
        max_stock: 15,
        expiry_date: '2026-04-25',
        rack_position: 'fridge_A2',
      },
      {
        item_id: 'RICE001',
        item_name: 'Rice',
        category: 'Grain',
        unit: 'kg',
        icon: '🌾',
        current_stock: 25,
        min_stock: 20,
        max_stock: 60,
        expiry_date: '2026-08-15',
        rack_position: 'shelf_B1',
      },
      {
        item_id: 'SAUCE001',
        item_name: 'Sambal',
        category: 'Sauce',
        unit: 'liter',
        icon: '🌶️',
        current_stock: 2,
        min_stock: 5,
        max_stock: 15,
        expiry_date: '2026-06-20',
        rack_position: 'shelf_C1',
      },
      {
        item_id: 'VEG001',
        item_name: 'Vegetables',
        category: 'Vegetable',
        unit: 'kg',
        icon: '🥬',
        current_stock: 1,
        min_stock: 5,
        max_stock: 20,
        expiry_date: '2026-04-23',
        rack_position: 'fridge_B1',
      },
      {
        item_id: 'DRINK001',
        item_name: 'Soft Drinks',
        category: 'Beverage',
        unit: 'pcs',
        icon: '🥤',
        current_stock: 150,
        min_stock: 50,
        max_stock: 200,
        expiry_date: '2026-07-10',
        rack_position: 'shelf_D1',
      },
      {
        item_id: 'FLOUR001',
        item_name: 'Flour',
        category: 'Grain',
        unit: 'kg',
        icon: '🫙',
        current_stock: 8,
        min_stock: 10,
        max_stock: 30,
        expiry_date: '2026-09-01',
        rack_position: 'shelf_B2',
      },
    ],
    racks: [
      {
        rack_id: 'fridge_A',
        rack_name: 'Refrigerator A',
        type: 'fridge',
        location_3d: { x: -4, y: 0, z: -3 },
        items: ['EGG001', 'CHICK001'],
      },
      {
        rack_id: 'fridge_B',
        rack_name: 'Refrigerator B',
        type: 'fridge',
        location_3d: { x: -4, y: 0, z: 2 },
        items: ['VEG001'],
      },
      {
        rack_id: 'shelf_B',
        rack_name: 'Dry Goods Shelf',
        type: 'shelf',
        location_3d: { x: 1, y: 0, z: -3 },
        items: ['RICE001', 'FLOUR001'],
      },
      {
        rack_id: 'shelf_C',
        rack_name: 'Sauce Station',
        type: 'shelf',
        location_3d: { x: 5, y: 0, z: -3 },
        items: ['SAUCE001'],
      },
      {
        rack_id: 'shelf_D',
        rack_name: 'Beverage Rack',
        type: 'shelf',
        location_3d: { x: 5, y: 0, z: 2 },
        items: ['DRINK001'],
      },
    ],
  },

  kiosk_2: {
    kiosk_id: 'kiosk_2',
    kiosk_name: 'Sunway Pyramid Outlet',
    items: [
      {
        item_id: 'BEEF001',
        item_name: 'Beef Patty',
        category: 'Protein',
        unit: 'kg',
        icon: '🥩',
        current_stock: 12,
        min_stock: 8,
        max_stock: 25,
        expiry_date: '2026-04-26',
        rack_position: 'fridge_A1',
      },
      {
        item_id: 'BUN001',
        item_name: 'Burger Buns',
        category: 'Bakery',
        unit: 'pcs',
        icon: '🍞',
        current_stock: 4,
        min_stock: 20,
        max_stock: 100,
        expiry_date: '2026-04-24',
        rack_position: 'shelf_A1',
      },
      {
        item_id: 'CHEESE001',
        item_name: 'Cheddar Cheese',
        category: 'Dairy',
        unit: 'kg',
        icon: '🧀',
        current_stock: 5,
        min_stock: 3,
        max_stock: 10,
        expiry_date: '2026-05-15',
        rack_position: 'fridge_B1',
      },
      {
        item_id: 'LETTUCE001',
        item_name: 'Lettuce',
        category: 'Vegetable',
        unit: 'kg',
        icon: '🥗',
        current_stock: 0,
        min_stock: 3,
        max_stock: 10,
        expiry_date: '2026-04-20',
        rack_position: 'fridge_B2',
      },
      {
        item_id: 'KETCHUP001',
        item_name: 'Ketchup',
        category: 'Sauce',
        unit: 'liter',
        icon: '🍅',
        current_stock: 8,
        min_stock: 5,
        max_stock: 20,
        expiry_date: '2026-11-30',
        rack_position: 'shelf_C1',
      },
      {
        item_id: 'FRIES001',
        item_name: 'Frozen Fries',
        category: 'Frozen',
        unit: 'kg',
        icon: '🍟',
        current_stock: 20,
        min_stock: 10,
        max_stock: 40,
        expiry_date: '2026-12-01',
        rack_position: 'freezer_A1',
      },
    ],
    racks: [
      {
        rack_id: 'fridge_A',
        rack_name: 'Protein Fridge',
        type: 'fridge',
        location_3d: { x: -4, y: 0, z: -3 },
        items: ['BEEF001'],
      },
      {
        rack_id: 'fridge_B',
        rack_name: 'Fresh Produce Fridge',
        type: 'fridge',
        location_3d: { x: -4, y: 0, z: 2 },
        items: ['CHEESE001', 'LETTUCE001'],
      },
      {
        rack_id: 'shelf_A',
        rack_name: 'Bakery Shelf',
        type: 'shelf',
        location_3d: { x: 1, y: 0, z: -3 },
        items: ['BUN001'],
      },
      {
        rack_id: 'shelf_C',
        rack_name: 'Condiments Shelf',
        type: 'shelf',
        location_3d: { x: 5, y: 0, z: -3 },
        items: ['KETCHUP001'],
      },
      {
        rack_id: 'freezer_A',
        rack_name: 'Freezer Unit',
        type: 'freezer',
        location_3d: { x: 5, y: 0, z: 2 },
        items: ['FRIES001'],
      },
    ],
  },

  kiosk_3: {
    kiosk_id: 'kiosk_3',
    kiosk_name: 'KLCC Concourse',
    items: [
      {
        item_id: 'NOODLE001',
        item_name: 'Noodles',
        category: 'Grain',
        unit: 'kg',
        icon: '🍜',
        current_stock: 30,
        min_stock: 15,
        max_stock: 50,
        expiry_date: '2026-10-20',
        rack_position: 'shelf_A1',
      },
      {
        item_id: 'SHRIMP001',
        item_name: 'Shrimp',
        category: 'Seafood',
        unit: 'kg',
        icon: '🍤',
        current_stock: 2,
        min_stock: 5,
        max_stock: 15,
        expiry_date: '2026-04-24',
        rack_position: 'fridge_A1',
      },
      {
        item_id: 'TOFU001',
        item_name: 'Tofu',
        category: 'Protein',
        unit: 'pcs',
        icon: '🫕',
        current_stock: 12,
        min_stock: 10,
        max_stock: 30,
        expiry_date: '2026-04-28',
        rack_position: 'fridge_A2',
      },
      {
        item_id: 'SOYSAUCE001',
        item_name: 'Soy Sauce',
        category: 'Sauce',
        unit: 'liter',
        icon: '🫙',
        current_stock: 10,
        min_stock: 5,
        max_stock: 20,
        expiry_date: '2027-01-15',
        rack_position: 'shelf_B1',
      },
      {
        item_id: 'SESAME001',
        item_name: 'Sesame Oil',
        category: 'Sauce',
        unit: 'liter',
        icon: '🫙',
        current_stock: 1,
        min_stock: 3,
        max_stock: 10,
        expiry_date: '2026-08-10',
        rack_position: 'shelf_B2',
      },
      {
        item_id: 'ICECREAM001',
        item_name: 'Ice Cream',
        category: 'Frozen',
        unit: 'pcs',
        icon: '🍦',
        current_stock: 45,
        min_stock: 20,
        max_stock: 80,
        expiry_date: '2026-06-30',
        rack_position: 'freezer_A1',
      },
    ],
    racks: [
      {
        rack_id: 'fridge_A',
        rack_name: 'Seafood Fridge',
        type: 'fridge',
        location_3d: { x: -4, y: 0, z: -3 },
        items: ['SHRIMP001', 'TOFU001'],
      },
      {
        rack_id: 'shelf_A',
        rack_name: 'Noodle Shelf',
        type: 'shelf',
        location_3d: { x: 1, y: 0, z: -3 },
        items: ['NOODLE001'],
      },
      {
        rack_id: 'shelf_B',
        rack_name: 'Sauce & Oil Shelf',
        type: 'shelf',
        location_3d: { x: 1, y: 0, z: 2 },
        items: ['SOYSAUCE001', 'SESAME001'],
      },
      {
        rack_id: 'freezer_A',
        rack_name: 'Ice Cream Freezer',
        type: 'freezer',
        location_3d: { x: 5, y: 0, z: 0 },
        items: ['ICECREAM001'],
      },
    ],
  },
};
